'use strict';

/**
 * @namespace Modernizr
 * @global
 *
 * @prop {boolean} android
 * @prop {boolean} android2
 * @prop {boolean} android3
 * @prop {boolean} android4
 * @prop {boolean} android5
 * @prop {boolean} android6
 * @prop {boolean} androidless
 * @prop {boolean} blink
 * @prop {boolean} chrome
 * @prop {boolean} ie
 * @prop {boolean} ie8
 * @prop {boolean} ie9
 * @prop {boolean} ie10
 * @prop {boolean} ie11
 * @prop {boolean} edge
 * @prop {boolean} edgeios
 * @prop {boolean} edgeandroid
 * @prop {boolean} intersectionobserver
 * @prop {boolean} ios
 * @prop {boolean} ipad
 * @prop {boolean} ipod
 * @prop {boolean} iphone
 * @prop {boolean} iphone4
 * @prop {boolean} iphone5
 * @prop {boolean} iphone6
 * @prop {boolean} iphone6plus
 * @prop {boolean} iphonex
 * @prop {boolean} linux
 * @prop {boolean} mac
 * @prop {boolean} maclike
 * @prop {boolean} meizu
 * @prop {boolean} meizunote
 * @prop {boolean} mobiledevice
 * @prop {boolean} moz
 * @prop {boolean} opera
 * @prop {boolean} redmi
 * @prop {boolean} redminote
 * @prop {boolean} retina
 * @prop {boolean} safari
 * @prop {boolean} safari
 * @prop {boolean} webkit
 * @prop {boolean} win
 * @prop {boolean} win7
 * @prop {boolean} win8
 * @prop {boolean} win10
 * @prop {boolean} winvista
 * @prop {boolean} winxp
 * @prop {boolean} win2000
 * @prop {boolean} windowsphone
 *
 * @prop {boolean} MessageChannel
 * @prop {boolean} adownload
 * @prop {boolean} ambientlight
 * @prop {boolean} animation
 * @prop {boolean} apng
 * @prop {boolean} appearance
 * @prop {boolean} applicationcache
 * @prop {boolean} arrow
 * @prop {boolean} atobbtoa
 * @prop {boolean} audio
 * @prop {boolean} audioloop
 * @prop {boolean} audiopreload
 * @prop {boolean} backdropfilter
 * @prop {boolean} backgroundblendmode
 * @prop {boolean} backgroundcliptext
 * @prop {boolean} backgroundsize
 * @prop {boolean} batteryapi
 * @prop {boolean} bdi
 * @prop {boolean} beacon
 * @prop {boolean} bgpositionshorthand
 * @prop {boolean} bgpositionxy
 * @prop {boolean} bgrepeatround
 * @prop {boolean} bgrepeatspace
 * @prop {boolean} bgsizecover
 * @prop {boolean} blobconstructor
 * @prop {boolean} bloburls
 * @prop {boolean} blobworkers
 * @prop {boolean} borderimage
 * @prop {boolean} borderradius
 * @prop {boolean} boxshadow
 * @prop {boolean} boxsizing
 * @prop {boolean} canvas
 * @prop {boolean} canvasblending
 * @prop {boolean} canvastext
 * @prop {boolean} canvaswinding
 * @prop {boolean} capture
 * @prop {boolean} checked
 * @prop {boolean} classlist
 * @prop {boolean} contains
 * @prop {boolean} contenteditable
 * @prop {boolean} contextmenu
 * @prop {boolean} cookies
 * @prop {boolean} cors
 * @prop {boolean} createelement-attrs
 * @prop {boolean} createelementattrs
 * @prop {boolean} cryptography
 * @prop {boolean} cssall
 * @prop {boolean} cssanimations
 * @prop {boolean} csscalc
 * @prop {boolean} csschunit
 * @prop {boolean} csscolumns
 * @prop {boolean} cssescape
 * @prop {boolean} cssexunit
 * @prop {boolean} cssfilters
 * @prop {boolean} cssgradients
 * @prop {boolean} cssgrid
 * @prop {boolean} cssgridlegacy
 * @prop {boolean} csshyphens
 * @prop {boolean} cssinvalid
 * @prop {boolean} cssmask
 * @prop {boolean} csspointerevents
 * @prop {boolean} csspositionsticky
 * @prop {boolean} csspseudoanimations
 * @prop {boolean} csspseudotransitions
 * @prop {boolean} cssreflections
 * @prop {boolean} cssremunit
 * @prop {boolean} cssresize
 * @prop {boolean} cssscrollbar
 * @prop {boolean} csstransforms
 * @prop {boolean} csstransforms3d
 * @prop {boolean} csstransformslevel2
 * @prop {boolean} csstransitions
 * @prop {boolean} cssvalid
 * @prop {boolean} cssvhunit
 * @prop {boolean} cssvmaxunit
 * @prop {boolean} cssvminunit
 * @prop {boolean} cssvwunit
 * @prop {boolean} cubicbezierrange
 * @prop {boolean} customelements
 * @prop {boolean} customevent
 * @prop {boolean} customprotocolhandler
 * @prop {boolean} dart
 * @prop {boolean} datachannel
 * @prop {boolean} datalistelem
 * @prop {boolean} dataset
 * @prop {boolean} datauri
 * @prop {boolean} dataview
 * @prop {boolean} dataworkers
 * @prop {boolean} details
 * @prop {boolean} devicemotion
 * @prop {boolean} deviceorientation
 * @prop {boolean} directory
 * @prop {boolean} display-runin
 * @prop {boolean} displaytable
 * @prop {boolean} documentfragment
 * @prop {boolean} ellipsis
 * @prop {boolean} emoji
 * @prop {boolean} es5
 * @prop {boolean} es5array
 * @prop {boolean} es5date
 * @prop {boolean} es5function
 * @prop {boolean} es5object
 * @prop {boolean} es5string
 * @prop {boolean} es5syntax
 * @prop {boolean} es5undefined
 * @prop {boolean} es6array
 * @prop {boolean} es6collections
 * @prop {boolean} es6math
 * @prop {boolean} es6number
 * @prop {boolean} es6object
 * @prop {boolean} es6string
 * @prop {boolean} eventlistener
 * @prop {boolean} eventsource
 * @prop {boolean} exiforientation
 * @prop {boolean} fetch
 * @prop {boolean} fileinput
 * @prop {boolean} filereader
 * @prop {boolean} filesystem
 * @prop {boolean} flash
 * @prop {boolean} flexbox
 * @prop {boolean} flexboxlegacy
 * @prop {boolean} flexboxtweener
 * @prop {boolean} flexwrap
 * @prop {boolean} fontface
 * @prop {boolean} forcetouch
 * @prop {boolean} formattribute
 * @prop {boolean} formvalidation
 * @prop {boolean} framed
 * @prop {boolean} fullscreen
 * @prop {boolean} gamepads
 * @prop {boolean} generatedcontent
 * @prop {boolean} generators
 * @prop {boolean} geolocation
 * @prop {boolean} getrandomvalues
 * @prop {boolean} getusermedia
 * @prop {boolean} hairline
 * @prop {boolean} hashchange
 * @prop {boolean} hidden
 * @prop {boolean} hiddenscroll
 * @prop {boolean} history
 * @prop {boolean} hovermq
 * @prop {boolean} hsla
 * @prop {boolean} htmlimports
 * @prop {boolean} ie8compat
 * @prop {boolean} imgcrossorigin
 * @prop {boolean} indexeddb
 * @prop {boolean} indexeddbblob
 * @prop {boolean} inlinesvg
 * @prop {boolean} input
 * @prop {boolean} inputformaction
 * @prop {boolean} inputformenctype
 * @prop {boolean} inputformmethod
 * @prop {boolean} inputformtarget
 * @prop {boolean} inputtypes
 * @prop {boolean} intl
 * @prop {boolean} jpeg2000
 * @prop {boolean} jpegxr
 * @prop {boolean} json
 * @prop {boolean} lastchild
 * @prop {boolean} ligatures
 * @prop {boolean} localizednumber
 * @prop {boolean} localstorage
 * @prop {boolean} lowbandwidth
 * @prop {boolean} lowbattery
 * @prop {boolean} matchmedia
 * @prop {boolean} mathml
 * @prop {boolean} mediaqueries
 * @prop {boolean} meter
 * @prop {boolean} microdata
 * @prop {boolean} multiplebgs
 * @prop {boolean} mutationobserver
 * @prop {boolean} notification
 * @prop {boolean} nthchild
 * @prop {boolean} objectfit
 * @prop {boolean} olreversed
 * @prop {boolean} oninput
 * @prop {boolean} opacity
 * @prop {boolean} outputelem
 * @prop {boolean} overflowscrolling
 * @prop {boolean} pagevisibility
 * @prop {boolean} passiveeventlisteners
 * @prop {boolean} peerconnection
 * @prop {boolean} performance
 * @prop {boolean} picture
 * @prop {boolean} placeholder
 * @prop {boolean} pointerevents
 * @prop {boolean} pointerlock
 * @prop {boolean} pointermq
 * @prop {boolean} postmessage
 * @prop {boolean} preserve3d
 * @prop {boolean} progressbar
 * @prop {boolean} promises
 * @prop {boolean} proximity
 * @prop {boolean} queryselector
 * @prop {boolean} quotamanagement
 * @prop {boolean} regions
 * @prop {boolean} requestanimationframe
 * @prop {boolean} requestautocomplete
 * @prop {boolean} rgba
 * @prop {boolean} ruby
 * @prop {boolean} sandbox
 * @prop {boolean} scriptasync
 * @prop {boolean} scriptdefer
 * @prop {boolean} scrollsnappoints
 * @prop {boolean} seamless
 * @prop {boolean} search
 * @prop {boolean} serviceworker
 * @prop {boolean} sessionstorage
 * @prop {boolean} shapes
 * @prop {boolean} sharedworkers
 * @prop {boolean} siblinggeneral
 * @prop {boolean} sizes
 * @prop {boolean} smil
 * @prop {boolean} softhyphens
 * @prop {boolean} softhyphensfind
 * @prop {boolean} speechrecognition
 * @prop {boolean} speechsynthesis
 * @prop {boolean} srcdoc
 * @prop {boolean} srcset
 * @prop {boolean} strictmode
 * @prop {boolean} stylescoped
 * @prop {boolean} subpixelfont
 * @prop {boolean} supports
 * @prop {boolean} svg
 * @prop {boolean} svgasimg
 * @prop {boolean} svgclippaths
 * @prop {boolean} svgfilters
 * @prop {boolean} svgforeignobject
 * @prop {boolean} target
 * @prop {boolean} template
 * @prop {boolean} templatestrings
 * @prop {boolean} textalignlast
 * @prop {boolean} textareamaxlength
 * @prop {boolean} textshadow
 * @prop {boolean} texttrackapi
 * @prop {boolean} time
 * @prop {boolean} todataurljpeg
 * @prop {boolean} todataurlpng
 * @prop {boolean} todataurlwebp
 * @prop {boolean} touchevents
 * @prop {boolean} track
 * @prop {boolean} transferables
 * @prop {boolean} typedarrays
 * @prop {boolean} unicode
 * @prop {boolean} unicoderange
 * @prop {boolean} unknownelements
 * @prop {boolean} urlparser
 * @prop {boolean} urlsearchparams
 * @prop {boolean} userdata
 * @prop {boolean} userselect
 * @prop {boolean} vibrate
 * @prop {boolean} video
 * @prop {boolean} videoautoplay
 * @prop {boolean} videocrossorigin
 * @prop {boolean} videoloop
 * @prop {boolean} videopreload
 * @prop {boolean} vml
 * @prop {boolean} webaudio
 * @prop {boolean} webgl
 * @prop {boolean} webglextensions
 * @prop {boolean} webintents
 * @prop {boolean} webp
 * @prop {boolean} webp-lossless
 * @prop {boolean} webpalpha
 * @prop {boolean} webpanimation
 * @prop {boolean} webplossless
 * @prop {boolean} websockets
 * @prop {boolean} websocketsbinary
 * @prop {boolean} websqldatabase
 * @prop {boolean} webworkers
 * @prop {boolean} willchange
 * @prop {boolean} wrapflow
 * @prop {boolean} xdomainrequest
 * @prop {boolean} xhr2
 * @prop {boolean} xhrresponsetype
 * @prop {boolean} xhrresponsetypearraybuffer
 * @prop {boolean} xhrresponsetypeblob
 * @prop {boolean} xhrresponsetypedocument
 * @prop {boolean} xhrresponsetypejson
 * @prop {boolean} xhrresponsetypetext
 */

/**
 * Own feature detects
 * @method addTest
 * @memberOf Modernizr
 * @param {string} query
 * @see {@link https://modernizr.com/docs#modernizr-addtest}
 */

/**
 * Check if the current browser window state matches a media query
 * @method mq
 * @memberOf Modernizr
 * @param {string} query
 * @see {@link https://modernizr.com/docs#modernizr-mq}
 * @example
 * Modernizr.mq('(min-width: 900px)');
 */
